In [1]:
!pip install pandas scikit-learn

Requirement already satisfied: pandas in /venv/main/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: scikit-learn in /venv/main/lib/python3.12/site-packages (1.5.1)
Requirement already satisfied: numpy>=1.26.0 in /venv/main/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /venv/main/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /venv/main/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /venv/main/lib/python3.12/site-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.6.0 in /venv/main/lib/python3.12/site-packages (from scikit-learn) (1.14.0)
Requirement already satisfied: joblib>=1.2.0 in /venv/main/lib/python3.12/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /venv/main/lib/python3.12/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in /venv/main/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [2]:
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score, cohen_kappa_score

retrieval = pd.read_json(
    "/workspace/SemDrug/data/drugbank_K-paths_d3_pool64_k10_mmr0.5_delta0.05.json",
    lines=True
)

debug = pd.read_csv("kpaths_no_proxy_regex_parse_debug.csv")

df = retrieval[["drug1_id", "drug2_id", "drug1_name", "drug2_name", "label_idx", "complete_evidence"]].copy()
df["pred"] = debug["predicted_label"].astype(int).values
df["gold"] = df["label_idx"].astype(int)
df["correct"] = df["pred"] == df["gold"]

def report_metrics(x, name):
    y_true = x["gold"]
    y_pred = x["pred"]
    print("=" * 80)
    print(name)
    print("n =", len(x))
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("Macro F1:", f1_score(y_true, y_pred, average="macro"))
    print("Kappa:", cohen_kappa_score(y_true, y_pred))
    print("Parse/no-match errors:", (debug.loc[x.index, "match_type"] == "No Match").mean())

report_metrics(df, "All")
report_metrics(df[df["complete_evidence"] == True], "complete_evidence=True")
report_metrics(df[df["complete_evidence"] == False], "complete_evidence=False")

print(pd.crosstab(df["complete_evidence"], df["correct"], normalize="index"))
print(pd.crosstab(df["complete_evidence"], df["correct"]))

ValueError: Length of values (31983) does not match length of index (31984)

In [3]:
from pathlib import Path
import pandas as pd

pred_path = Path("/workspace/SemDrug/outputs/drugbank_K-paths_d3_pool64_k10_mmr0.5_delta0.05_kg/predictions.csv")

pred = pd.read_csv(pred_path)

print("pred rows:", len(pred))
print("pred columns:", pred.columns.tolist())
display(pred.head())
display(pred.tail())

pred rows: 31984
pred columns: ['prediction']

                                          prediction
0  ##Answer: Glycopyrronium may increase the anti...
1  ##Answer: Aclidinium may increase the antichol...
2  ##Answer: Umeclidinium may increase the antich...
3  ##Answer: Umeclidinium may increase the antich...
4  ##Answer: Pirenzepine may increase the anticho...

                                              prediction
31979  ##Answer: Venlafaxine may decrease the metabol...
31980  ##Answer: Venlafaxine may increase the tachyca...
31981  ##Answer: Venlafaxine may increase the tachyca...
31982  ##Answer: Venlafaxine may increase the tachyca...
31983  ##Answer: Duloxetine may increase the tachycar...

In [4]:
print("retrieval:", len(retrieval))
print("pred:", len(pred))
print("debug:", len(debug))

print("\npred columns:")
print(pred.columns.tolist())

print("\ndebug columns:")
print(debug.columns.tolist())

display(pred.head())
display(pred.tail())

display(debug.head())
display(debug.tail())

retrieval: 31984
pred: 31984
debug: 31983

pred columns:
['prediction']

debug columns:
['i', 'drug1', 'drug2', 'raw_prediction', 'extracted_prediction', 'predicted_label', 'match_type']

                                          prediction
0  ##Answer: Glycopyrronium may increase the anti...
1  ##Answer: Aclidinium may increase the antichol...
2  ##Answer: Umeclidinium may increase the antich...
3  ##Answer: Umeclidinium may increase the antich...
4  ##Answer: Pirenzepine may increase the anticho...

                                              prediction
31979  ##Answer: Venlafaxine may decrease the metabol...
31980  ##Answer: Venlafaxine may increase the tachyca...
31981  ##Answer: Venlafaxine may increase the tachyca...
31982  ##Answer: Venlafaxine may increase the tachyca...
31983  ##Answer: Duloxetine may increase the tachycar...

,i,drug1,drug2,raw_prediction,extracted_prediction,predicted_label,match_type
0,0,Glycopyrronium,Cyclopentolate,##Answer: Glycopyrronium may increase the anti...,Glycopyrronium may increase the anticholinergi...,1,Exact Match (With Drug Names)
1,1,Aclidinium,Pirenzepine,##Answer: Aclidinium may increase the antichol...,Aclidinium may increase the anticholinergic ac...,1,Exact Match (With Drug Names)
2,2,Umeclidinium,Pirenzepine,##Answer: Umeclidinium may increase the antich...,Umeclidinium may increase the anticholinergic ...,1,Exact Match (With Drug Names)
3,3,Umeclidinium,Pipecuronium,##Answer: Umeclidinium may increase the antich...,Umeclidinium may increase the anticholinergic ...,1,Exact Match (With Drug Names)
4,4,Pirenzepine,Mianserin,##Answer: Pirenzepine may increase the anticho...,Pirenzepine may increase the anticholinergic a...,1,Exact Match (With Drug Names)

,i,drug1,drug2,raw_prediction,extracted_prediction,predicted_label,match_type
31978,31979,Venlafaxine,Arformoterol,##Answer: Venlafaxine may decrease the metabol...,Venlafaxine may decrease the metabolism of Arf...,46,Exact Match (With Drug Names)
31979,31980,Venlafaxine,Naphazoline,##Answer: Venlafaxine may increase the tachyca...,Venlafaxine may increase the tachycardic activ...,84,Exact Match (With Drug Names)
31980,31981,Venlafaxine,Terbutaline,##Answer: Venlafaxine may increase the tachyca...,Venlafaxine may increase the tachycardic activ...,84,Exact Match (With Drug Names)
31981,31982,Venlafaxine,Pirbuterol,##Answer: Venlafaxine may increase the tachyca...,Venlafaxine may increase the tachycardic activ...,84,Exact Match (With Drug Names)
31982,31983,Duloxetine,Dipivefrin,##Answer: Duloxetine may increase the tachycar...,Duloxetine may increase the tachycardic activi...,84,Exact Match (With Drug Names)

In [6]:
debug = pd.read_json(
    "/workspace/SemDrug/drugbank_regex_parse_debug.jsonl",
    lines=True
)

print("debug rows:", len(debug))
display(debug.head())
display(debug.tail())

debug rows: 31983

,i,drug1,drug2,raw_prediction,extracted_prediction,predicted_label,match_type
0,0,Glycopyrronium,Cyclopentolate,##Answer: Glycopyrronium may increase the anti...,Glycopyrronium may increase the anticholinergi...,1,Exact Match (With Drug Names)
1,1,Aclidinium,Pirenzepine,##Answer: Aclidinium may increase the antichol...,Aclidinium may increase the anticholinergic ac...,1,Exact Match (With Drug Names)
2,2,Umeclidinium,Pirenzepine,##Answer: Umeclidinium may increase the antich...,Umeclidinium may increase the anticholinergic ...,1,Exact Match (With Drug Names)
3,3,Umeclidinium,Pipecuronium,##Answer: Umeclidinium may increase the antich...,Umeclidinium may increase the anticholinergic ...,1,Exact Match (With Drug Names)
4,4,Pirenzepine,Mianserin,##Answer: Pirenzepine may increase the anticho...,Pirenzepine may increase the anticholinergic a...,1,Exact Match (With Drug Names)

,i,drug1,drug2,raw_prediction,extracted_prediction,predicted_label,match_type
31978,31979,Venlafaxine,Arformoterol,##Answer: Venlafaxine may decrease the metabol...,Venlafaxine may decrease the metabolism of Arf...,46,Exact Match (With Drug Names)
31979,31980,Venlafaxine,Naphazoline,##Answer: Venlafaxine may increase the tachyca...,Venlafaxine may increase the tachycardic activ...,84,Exact Match (With Drug Names)
31980,31981,Venlafaxine,Terbutaline,##Answer: Venlafaxine may increase the tachyca...,Venlafaxine may increase the tachycardic activ...,84,Exact Match (With Drug Names)
31981,31982,Venlafaxine,Pirbuterol,##Answer: Venlafaxine may increase the tachyca...,Venlafaxine may increase the tachycardic activ...,84,Exact Match (With Drug Names)
31982,31983,Duloxetine,Dipivefrin,##Answer: Duloxetine may increase the tachycar...,Duloxetine may increase the tachycardic activi...,84,Exact Match (With Drug Names)

In [7]:
import ast
import re
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score, cohen_kappa_score


PROJECT_ROOT = Path("/workspace/SemDrug")

RETRIEVAL_PATH = PROJECT_ROOT / "data/drugbank_K-paths_d3_pool64_k10_mmr0.5_delta0.05.json"

PRED_PATH = (
    PROJECT_ROOT
    / "outputs/drugbank_K-paths_d3_pool64_k10_mmr0.5_delta0.05_kg/predictions.csv"
)


def read_json_auto(path):
    path = Path(path)
    with open(path, "r", encoding="utf-8") as f:
        first = ""
        while True:
            ch = f.read(1)
            if not ch:
                break
            if not ch.isspace():
                first = ch
                break

    if first == "[":
        return pd.read_json(path)
    return pd.read_json(path, lines=True)


def load_drugbank_labels_from_source(project_root):
    """
    Load DRUGBANK_LABELS or DRUGBANK_OPTIONS from existing source files
    without importing the scripts.
    """
    candidate_files = [
        project_root / "semdrug/evaluate_llm_regex.py",
        project_root / "llm/run_llm_server.py",
        project_root / "semdrug/llm_inference.py",
    ]

    candidate_names = [
        "DRUGBANK_LABELS",
        "DRUGBANK_OPTIONS",
        "drugbank_relation_id_to_name",
    ]

    for file_path in candidate_files:
        if not file_path.exists():
            continue

        source = file_path.read_text(encoding="utf-8")
        tree = ast.parse(source)

        for node in tree.body:
            if not isinstance(node, ast.Assign):
                continue

            target_names = [
                t.id for t in node.targets
                if isinstance(t, ast.Name)
            ]

            for name in candidate_names:
                if name not in target_names:
                    continue

                try:
                    d = ast.literal_eval(node.value)
                except Exception:
                    continue

                if not isinstance(d, dict) or len(d) < 80:
                    continue

                d = {int(k): str(v) for k, v in d.items()}

                # Case: relation IDs 23..108 need reindexing to 0..85.
                keys = sorted(d.keys())
                if min(keys) == 23 and max(keys) == 108:
                    d = {k - 23: v for k, v in d.items()}

                if len(d) >= 86 and set(range(86)).issubset(set(d.keys())):
                    print(f"Loaded DrugBank labels from: {file_path}")
                    return {i: d[i] for i in range(86)}

    raise RuntimeError(
        "Could not load DrugBank labels/options from source files. "
        "Please check DRUGBANK_LABELS or DRUGBANK_OPTIONS exists."
    )


retrieval = read_json_auto(RETRIEVAL_PATH).reset_index(drop=True)
pred = pd.read_csv(PRED_PATH).reset_index(drop=True)

print("retrieval rows:", len(retrieval))
print("prediction rows:", len(pred))
print("prediction columns:", pred.columns.tolist())

assert len(retrieval) == len(pred), (len(retrieval), len(pred))

DRUGBANK_LABELS = load_drugbank_labels_from_source(PROJECT_ROOT)
print("Loaded labels:", len(DRUGBANK_LABELS))

retrieval rows: 31984
prediction rows: 31984
prediction columns: ['prediction']
Loaded DrugBank labels from: /workspace/SemDrug/llm/run_llm_server.py
Loaded labels: 86

In [8]:
CUSTOM_STOPWORDS = {
    "used", "a", "be", "is", "it", "may", "can", "the", "of", "and", "by",
    "when", "combined", "with", "risk", "to", "in", "drug1", "drug2", "risks",
    "activities", "activity", "effects", "effect",
}

def normalize_bool(x):
    if isinstance(x, bool):
        return x
    if isinstance(x, (int, float)):
        return bool(x)
    if isinstance(x, str):
        return x.strip().lower() in {"true", "1", "yes"}
    return False


def get_prediction_column(pred_df):
    priority = [
        "prediction",
        "predictions",
        "response",
        "output",
        "raw_output",
        "generated_text",
        "generation",
        "answer",
        "text",
    ]

    for col in priority:
        if col in pred_df.columns:
            return col

    object_cols = pred_df.select_dtypes(include=["object"]).columns.tolist()

    if len(object_cols) == 1:
        return object_cols[0]

    print("Available columns:", pred_df.columns.tolist())
    print("Object columns:", object_cols)

    raise ValueError(
        "Cannot infer prediction column. "
        "Please manually set PRED_COL to the column containing LLM output."
    )


PRED_COL = get_prediction_column(pred)
print("Using prediction column:", PRED_COL)


def strip_leading_option_number(s):
    if not isinstance(s, str):
        return s

    s = s.strip()

    # Remove "- 12. ...", "12) ...", "Option 12: ..."
    s = re.sub(
        r"^\s*[-*\u2022]?\s*(?:option\s*)?\d+\s*[\.\)\:\-]\s*",
        "",
        s,
        flags=re.IGNORECASE,
    )

    return s.strip()


def extract_answer(text):
    """
    Extract answer after ##Answer:. If missing, use first non-empty line.
    """
    if not isinstance(text, str):
        return "", "Parse Error"

    raw = text.strip()

    if not raw:
        return "", "Parse Error"

    # Match ##Answer: with flexible spacing/capitalization.
    m = re.search(r"##\s*Answer\s*:\s*(.*)", raw, flags=re.IGNORECASE | re.DOTALL)

    if m:
        ans = m.group(1).strip()
        # Usually answer should be first line only.
        ans = ans.splitlines()[0].strip()
        ans = ans.strip("\"'` ")
        ans = strip_leading_option_number(ans)
        return ans, "Extracted"

    # Fallback: use first non-empty line.
    for line in raw.splitlines():
        line = line.strip()
        if line:
            line = line.strip("\"'` ")
            line = strip_leading_option_number(line)
            return line, "No Answer Marker"

    return "", "Parse Error"


def reduce_word(word):
    reduction_map = {
        "effectiveness": "effect",
        "effects": "effect",
        "activities": "activity",
        "increased": "increase",
        "increases": "increase",
        "increasing": "increase",
        "decreased": "decrease",
        "decreases": "decrease",
        "decreasing": "decrease",
        "additive": "increase",
    }
    return reduction_map.get(word, word)


def preprocess_text(text):
    if not isinstance(text, str):
        return ""

    text = text.lower()
    text = text.replace("{u}", "drug1").replace("{v}", "drug2")
    text = re.sub(r"[^\w\s]", " ", text)

    tokens = re.findall(r"\b\w+\b", text)

    tokens = [
        reduce_word(t)
        for t in tokens
        if t not in CUSTOM_STOPWORDS and len(t) > 1
    ]

    return " ".join(tokens)


def canonicalize_drug_name(x):
    if not isinstance(x, str):
        return ""
    return re.sub(r"[^\w\s]", " ", x.lower()).strip()


def match_drugbank_label(answer, drug1_name, drug2_name):
    """
    Returns: pred_label, match_type
    """
    if not isinstance(answer, str) or not answer.strip():
        return 48, "Parse Error"

    answer_clean = answer.strip().lower()
    answer_clean = strip_leading_option_number(answer_clean)
    answer_clean = answer_clean.replace("drug a", "drug1").replace("drug b", "drug2")
    answer_clean = answer_clean.replace("drug x", "drug1").replace("drug y", "drug2")

    d1 = canonicalize_drug_name(drug1_name)
    d2 = canonicalize_drug_name(drug2_name)

    # Build candidate option texts with actual drug names.
    candidates = {}
    for k, template in DRUGBANK_LABELS.items():
        txt = str(template).lower()
        txt = txt.replace("{u}", d1 if d1 else "drug1")
        txt = txt.replace("{v}", d2 if d2 else "drug2")
        candidates[int(k)] = txt

    answer_proc = preprocess_text(answer_clean)

    # 1. Exact processed match with drug names.
    for k, txt in candidates.items():
        if preprocess_text(txt) == answer_proc:
            return k, "Exact Match"

    # 2. Remove actual drug names from both sides.
    answer_no_drugs = answer_clean

    if d1:
        answer_no_drugs = answer_no_drugs.replace(d1, " ")
    if d2:
        answer_no_drugs = answer_no_drugs.replace(d2, " ")

    answer_no_drugs_proc = preprocess_text(answer_no_drugs)

    for k, txt in candidates.items():
        txt_no_drugs = txt
        if d1:
            txt_no_drugs = txt_no_drugs.replace(d1, " ")
        if d2:
            txt_no_drugs = txt_no_drugs.replace(d2, " ")

        if preprocess_text(txt_no_drugs) == answer_no_drugs_proc:
            return k, "Exact Match Without Drug Names"

    # 3. Match against generic Drug1/Drug2 option text.
    generic_candidates = {
        int(k): str(v).lower().replace("{u}", "drug1").replace("{v}", "drug2")
        for k, v in DRUGBANK_LABELS.items()
    }

    generic_answer = answer_clean
    if d1:
        generic_answer = generic_answer.replace(d1, "drug1")
    if d2:
        generic_answer = generic_answer.replace(d2, "drug2")

    generic_answer_proc = preprocess_text(generic_answer)

    for k, txt in generic_candidates.items():
        if preprocess_text(txt) == generic_answer_proc:
            return k, "Exact Match Generic Drug Names"

    return 48, "No Match"


rows = []

for i in range(len(retrieval)):
    r = retrieval.iloc[i]
    raw_output = pred.iloc[i][PRED_COL]

    extracted, extract_type = extract_answer(raw_output)

    parsed_label, match_type = match_drugbank_label(
        extracted,
        r.get("drug1_name", ""),
        r.get("drug2_name", ""),
    )

    complete_evidence = normalize_bool(r.get("complete_evidence", False))

    rows.append({
        "row_idx": i,
        "drug1_id": r.get("drug1_id"),
        "drug2_id": r.get("drug2_id"),
        "drug1_name": r.get("drug1_name"),
        "drug2_name": r.get("drug2_name"),
        "gold": int(r.get("label_idx")),
        "pred": int(parsed_label),
        "correct": int(parsed_label) == int(r.get("label_idx")),
        "complete_evidence": complete_evidence,
        "extract_type": extract_type,
        "match_type": match_type,
        "extracted_prediction": extracted,
        "raw_output": raw_output,
    })

parsed = pd.DataFrame(rows)

print("parsed rows:", len(parsed))
print("\nExtract type:")
print(parsed["extract_type"].value_counts(dropna=False))
print("\nMatch type:")
print(parsed["match_type"].value_counts(dropna=False))

acc = accuracy_score(parsed["gold"], parsed["pred"])
f1 = f1_score(
    parsed["gold"],
    parsed["pred"],
    labels=list(range(86)),
    average="macro",
    zero_division=0,
)
kappa = cohen_kappa_score(parsed["gold"], parsed["pred"])

print("\nOverall")
print("Accuracy:", acc)
print("Macro F1:", f1)
print("Kappa:", kappa)
print("Parse/No Match rate:", parsed["match_type"].isin(["Parse Error", "No Match"]).mean())

Using prediction column: prediction
parsed rows: 31984

Extract type:
extract_type
Extracted           31983
No Answer Marker        1
Name: count, dtype: int64

Match type:
match_type
Exact Match    31880
No Match         104
Name: count, dtype: int64

Overall
Accuracy: 0.5357053526763381
Macro F1: 0.40169925083314395
Kappa: 0.45316456892413204
Parse/No Match rate: 0.0032516258129064533

In [11]:
def normalize_bool(x):
    if pd.isna(x):
        return False

    if isinstance(x, (bool, np.bool_)):
        return bool(x)

    if isinstance(x, (int, np.integer)):
        return bool(x)

    if isinstance(x, (float, np.floating)):
        return bool(x)

    if isinstance(x, str):
        return x.strip().lower() in {"true", "1", "yes", "y"}

    return False

In [12]:
parsed["complete_evidence"] = retrieval["complete_evidence"].apply(normalize_bool).values
parsed["correct"] = parsed["pred"].astype(int) == parsed["gold"].astype(int)

print(parsed["complete_evidence"].value_counts(dropna=False))

complete_evidence
True     27983
False     4001
Name: count, dtype: int64

In [13]:
def report_metrics(df, name):
    if len(df) == 0:
        print(name, "is empty")
        return

    print("=" * 80)
    print(name)
    print("n =", len(df))
    print("Accuracy:", accuracy_score(df["gold"], df["pred"]))
    print(
        "Macro F1:",
        f1_score(
            df["gold"],
            df["pred"],
            labels=list(range(86)),
            average="macro",
            zero_division=0,
        )
    )
    print("Kappa:", cohen_kappa_score(df["gold"], df["pred"]))
    print("Parse/No Match rate:", df["match_type"].isin(["Parse Error", "No Match"]).mean())


report_metrics(parsed, "All")
report_metrics(parsed[parsed["complete_evidence"] == True], "complete_evidence=True")
report_metrics(parsed[parsed["complete_evidence"] == False], "complete_evidence=False")

print("\nCorrectness by complete_evidence, normalized:")
display(pd.crosstab(parsed["complete_evidence"], parsed["correct"], normalize="index"))

print("\nCorrectness by complete_evidence, count:")
display(pd.crosstab(parsed["complete_evidence"], parsed["correct"]))

print("\nMatch type by complete_evidence, normalized:")
display(pd.crosstab(parsed["complete_evidence"], parsed["match_type"], normalize="index"))

print("\nMatch type by complete_evidence, count:")
display(pd.crosstab(parsed["complete_evidence"], parsed["match_type"]))

================================================================================
All
n = 31984
Accuracy: 0.5357053526763381
Macro F1: 0.40169925083314395
Kappa: 0.45316456892413204
Parse/No Match rate: 0.0032516258129064533
================================================================================
complete_evidence=True
n = 27983
Accuracy: 0.5480470285530501
Macro F1: 0.4048962621430099
Kappa: 0.4711508944118389
Parse/No Match rate: 0.0036808062037665726
================================================================================
complete_evidence=False
n = 4001
Accuracy: 0.44938765308672834
Macro F1: 0.16809322533257395
Kappa: 0.32057515295571526
Parse/No Match rate: 0.00024993751562109475

Correctness by complete_evidence, normalized:

correct               False     True
complete_evidence
False              0.550612  0.449388
True               0.451953  0.548047

Correctness by complete_evidence, count:

correct            False  True
complete_evidence
False               2203   1798
True               12647  15336

Match type by complete_evidence, normalized:

match_type         Exact Match  No Match
complete_evidence
False                 0.999750  0.000250
True                  0.996319  0.003681

Match type by complete_evidence, count:

match_type         Exact Match  No Match
complete_evidence
False                     4000         1
True                     27880       103

In [10]:
print(retrieval["complete_evidence"].dtype)
print(retrieval["complete_evidence"].value_counts(dropna=False))
print(type(retrieval.loc[0, "complete_evidence"]), retrieval.loc[0, "complete_evidence"])

bool
complete_evidence
True     27983
False     4001
Name: count, dtype: int64
<class 'numpy.bool_'> True

In [15]:
import sys
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score, cohen_kappa_score

PROJECT_ROOT = Path("/workspace/SemDrug")
sys.path.insert(0, str(PROJECT_ROOT))

import llm.evaluate_llm_regex as ev

PRED_PATH = "/workspace/SemDrug/outputs/drugbank_K-paths_d3_pool64_k10_mmr0.5_delta0.05_kg"
RETRIEVAL_PATH = "/workspace/SemDrug/data/drugbank_K-paths_d3_pool64_k10_mmr0.5_delta0.05.json"

dataset_string = "drugbank"
model_style = "auto"

# Load exactly as official evaluator.
test_df = ev.load_test_dataset(ev.TEST_SET_PATH[dataset_string]).reset_index(drop=True)

if "label_idx" in test_df.columns:
    gold = test_df["label_idx"].astype(int)
elif "Y" in test_df.columns:
    gold = test_df["Y"].astype(int)
else:
    raise ValueError(test_df.columns.tolist())

pred_df = ev.load_dataset_predictions(PRED_PATH, test_df).reset_index(drop=True)
raw_predictions = pred_df["prediction"].tolist()

extract_fn = ev.EXTRACTOR_MAP[model_style]

official_preds, official_errors = ev.parse_drugbank_outputs(
    raw_predictions,
    test_df["drug1_name"],
    test_df["drug2_name"],
    extract_fn,
)

official_preds = pd.Series(official_preds).astype(int)

print("test rows:", len(test_df))
print("pred rows:", len(pred_df))
print("parsed rows:", len(official_preds))
print("errors:", len(official_errors), len(official_errors) / len(official_preds))

print("Official-style metrics:")
print("Accuracy:", accuracy_score(gold, official_preds))
print("Macro F1 official-style:", f1_score(gold, official_preds, average=None).mean())
print("Kappa:", cohen_kappa_score(gold, official_preds))

06/12/2026 12:51:05 - INFO - llm.evaluate_llm_regex -   Loading test dataset from: data/drugbank/drugbank_test_set.json
06/12/2026 12:51:06 - INFO - llm.evaluate_llm_regex -   loading prediction csv file
06/12/2026 12:51:19 - INFO - llm.evaluate_llm_regex -   Total predictions: 31984
06/12/2026 12:51:19 - INFO - llm.evaluate_llm_regex -   Parse errors: 1 (0.00%)
06/12/2026 12:51:19 - INFO - llm.evaluate_llm_regex -   Semantic mismatches: 162 (0.51%)
06/12/2026 12:51:19 - INFO - llm.evaluate_llm_regex -   Total error-labeled predictions: 163 (0.51%)

Debug rows before saving: 31983

06/12/2026 12:51:20 - INFO - llm.evaluate_llm_regex -   Saved DrugBank regex parse debug to drugbank_regex_parse_debug.csv

test rows: 31984
pred rows: 31984
parsed rows: 31984
errors: 163 0.005096298149074537
Official-style metrics:
Accuracy: 0.5680027513756879
Macro F1 official-style: 0.4055091436394119
Kappa: 0.48982818021745844

In [ ]:
def read_json_auto(path):
    try:
        return pd.read_json(path, lines=True)
    except ValueError:
        return pd.read_json(path)

retrieval = read_json_auto(RETRIEVAL_PATH).reset_index(drop=True)

print("retrieval rows:", len(retrieval))
print("test rows:", len(test_df))

assert len(retrieval) == len(test_df), (len(retrieval), len(test_df))

# Sanity check order.
check_cols = ["drug1_id", "drug2_id", "label_idx"]
for c in check_cols:
    if c in retrieval.columns and c in test_df.columns:
        same = (retrieval[c].astype(str).values == test_df[c].astype(str).values).mean()
        print(c, "same ratio:", same)

complete_evidence = retrieval["complete_evidence"].astype(bool).values

parsed_official = test_df[[
    "Drug1_ID", "Drug2_ID", "drug1_name", "drug2_name"
]].copy()

parsed_official["gold"] = gold.values
parsed_official["pred"] = official_preds.values
parsed_official["correct"] = parsed_official["gold"] == parsed_official["pred"]
parsed_official["complete_evidence"] = complete_evidence

retrieval rows: 31984
test rows: 31984

KeyError: "['Drug1_id', 'Drug2_id'] not in index"